language: android
sudo: false
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./gradlew assembleDevelopDebug
